{% set version = "0.3.7" %}

package:
  name: iqplot
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/i/iqplot/iqplot-{{ version }}.tar.gz
  sha256: 8e5634bb9f88c3485790d0dc6953043e7115db1cefcbdebc116d100bde7829e0

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - bokeh
    - colorcet
    - numpy
    - pandas
    - python
    - xarray
    - python >={{ python_min }}

test:
  imports:
    - iqplot
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/justinbois/iqplot
  summary: Generate Bokeh plots for data sets with one quantitative variable.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danielnachun
